[default.probe]
protocol = "Swd"
speed = 2000

[default.flashing]
enabled = true

[default.reset]
enabled = true

[default.general]
chip = "stm32f730V8Tx"
chip_descriptions = ["stm32f730v8t6.yaml"]

[default.rtt]
enabled = true
timeout = 2
show_timestamps = true

