[tasks.objcopy]
command = "cargo"
args = [
    "objcopy",
    "--bin", "rustworks",
    "--",
    "-O", "binary",
    "../target/thumbv7em-none-eabihf/debug/rustworks.bin"
]

[tasks.dfu]
command = "dfu-util"
args = [
    "-d", "0483:df11",
    "-a", "0",
    "-s", "0x90000000:leave",
    "-D", "../target/thumbv7em-none-eabihf/debug/rustworks.bin"
]
dependencies = ["objcopy"]

[tasks.flash]
command = "cargo"
args = [
    "flash",
    "--chip",
		"stm32f730V8Tx",
    "--chip-description-path",
		"stm32f730v8t6.yaml",
]
