[default.probe]
protocol = "Swd"
speed = 2000

[default.flashing]
enabled = true

[default.reset]
enabled = true
halt_afterwards = true

[default.general]
chip = "stm32f730V8Tx"
chip_descriptions = ["stm32f730v8t6.yaml"]

[default.rtt]
enabled = false
timeout = 2
show_timestamps = true

[default.gdb] 
enabled = true
gdb_connection_string = "localhost:1337"

